### PR TITLE
Enabling updates to /etc/resolve.conf either manually or using DHCP supplied DNS IP

### PR DESCRIPTION
**Pull request by vishwabmc**
Provide dbus APIs to provide nameserver IPs and update them in /etc/resolv.conf
Also, register watch for /run/systemd/netif/state for DHCP and take the DNS entries and update /etc/resolv.conf

---
This change is [Reviewable](https://reviewable.io/reviews/openbmc/phosphor-networkd/13)

### CODE REVIEW

**Comment by mdmillerii** [comment]
In addition to the comments below:

You didn't supply a service file (which, I know, goes in the openbmc repository), but how do you anticipate the requirement to allow the administrator to specify DNS servers overriding DHCP supplied ones?  By stopping the service?

I anticipated a setting that would change the target of the /etc/resolv.conf link, with rest names "static" (file, or symlink to file), "dhcp" (symlink to file in /run) and maybe "bootloader" (to the /proc/net/pnp file, I admit this is extra credit).

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[netman.py, line 234 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDI2fxRrYao8mvgynX:-KEDI2fyCdqh9Ovv3pFP:-65460939) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman.py#L234)):*
So how does one clear the list?

And if we get some valid and some invalid addresses we write the valid ones?

---

*[netman_watch_dns.c, line 138 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDO2rtBtp4BM_3imHQ:-KEDO2rtBtp4BM_3imHR:-1315850866) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L138)):*
So this code is parsing the state file which says in the first line
`# This is private data. Do not parse.`

And there is an exported header with functions that will do the parsing and directory find.

So why not use them?

There is even a function that gets the addresses from all links.

---

*[netman_watch_dns.c, line 291 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDKxGMqqG7Jk6Nhqrk:-KEDKxGMqqG7Jk6Nhqrl:-682229136) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L291)):*
So this is a runtime sized array ...

---

*[netman_watch_dns.c, line 293 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDLxqhf6A_o9YxLNGI:-KEDLxqiAsnOTtV1cd4D:850714547) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L293)):*
... that is cleared to NUL bytes

---

*[netman_watch_dns.c, line 313 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDKeTToUVYPaiXbu-e:-KEDKeTToUVYPaiXbu-f:-947761345) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L313)):*
This `strncpy` now relies on the NUL fill to terminate the string.

This is using lots of `strlen` calls when it could just use a bit of pointer math.

---

*[netman_watch_dns.c, line 314 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDKXM-5I669EGGfxBk:-KEDKXM08aAn9jTTd-Qh:-2030353884) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L314)):*
`strncat` of an empty string is always a NO OP and never makes sense.
Nor passing a string with an extra `\0` in it to `str*` functions.

Instead, why not `strdup`, or better yet `strndup (argv[1], sstate_file - argv[1])` ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-:-KEDRBuIts82DNyBaAzE:2095784123)*

**Comment by vishwabmc** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[netman.py, line 234 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDI2fxRrYao8mvgynX:-KEG9h9kf98e9R9O9zmp:1273058672) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman.py#L234)):*
Why do we need to clear anything here ?. We do not maintain any cache here.

Yes, if we have mix of valid and invalid inputs, rather than rejecting all, atl-east process the good ones.

---

*[netman_watch_dns.c, line 138 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDO2rtBtp4BM_3imHQ:-KEGApX-LyDv2CzkkPcY:-1041737153) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L138)):*
Any line that does not  begin with DNS will not be processed. 

Also, those API's want the Interface information to be passed to get the DNS entries. But is that really making sense  to tie a NIC to a DNS entry ?. It does not make much sense to me since at a resolver level, it does not really matter whether I use eth0 or eth1 until we go down the stack.before we choose right interface ?. Also, we have just eth0 here. 

---

*[netman_watch_dns.c, line 291 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDKxGMqqG7Jk6Nhqrk:-KEGA_-bVZB3AgieRFOm:949920547) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L291)):*
Correct and its valid. Do you see any issues with it ?

---

*[netman_watch_dns.c, line 293 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDLxqhf6A_o9YxLNGI:-KEGAeVWTigQxRtvEtQK:-2141960394) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L293)):*
Not sure I understood the comment.. Sorry ...

---

*[netman_watch_dns.c, line 313 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDKeTToUVYPaiXbu-e:-KEGCN8xyZZujUFY1Qtf:-2025110277) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L313)):*
The allocation for netif_state is based on the  length of argv[1] so I am not seeing a case where it can fail.. Are you seeing some path ?.

Pointer math may not work here since these are 2 different base addresses.

---

*[netman_watch_dns.c, line 314 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDKXM-5I669EGGfxBk:-KEGCj9cRddU6zSjp7lb:794063890) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L314)):*
Agree with you on strcat but we do not ever have a null string here since check for argv[1] null is done in the beginning.

In the strndup pasted ,the (state_file - argv[1]) will result in undefined since we are doing a subtract of 2 different base addresses.. 

At the min, should it not be: netif_dir = stndup(argv[1], strlen(argv[1]) - strlen(state_file)) ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13)*

**Comment by vishwabmc** [comment]
Answered in email.

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-:-KEGGk9VpvBZx_TQJraw:2054857167)*

**Comment by vishwabmc** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[netman_watch_dns.c, line 314 \[r1\]](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13#-KEDKXM-5I669EGGfxBk:-KEGHxIUoj8w2keXVe0b:2055124259) ([raw file](https://github.com/openbmc/phosphor-networkd/blob/410c3164046c6a7c9df1884d112edb9d8dd68e5d/netman_watch_dns.c#L314)):*
Or were you saying something like:

netif_dir = strdup(argv[1], argv[1] - strrchr(argv[1], '/')) ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openbmc/phosphor-networkd/13)*

**Comment by williamspatrick** [comment]
There are comments here to resolve.  Are we expecting an additional patch set?

**Pull request merged**
